apiVersion: v1
kind: Service
metadata:
  name: memsql-dataapi
  namespace: singlestore
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/component: aggregator
    app.kubernetes.io/name: memsql-cluster
  sessionAffinity: None
  type: ClusterIP
