apiVersion: memsql.com/v1alpha1
kind: MemsqlCluster
metadata:
  name: sdb-cluster
  namespace: singlestore
spec:
  license: "xxxxx"
  adminHashedPassword: "xxxxx"
  nodeImage:
    repository: xxx/singlestore/node
    tag: alma-8.9.18-a279bf2484

  redundancyLevel: 2

  globalSpec:
    globalVariables:
      enable_bottomless: "ON"

  serviceSpec:
    type: "NodePort"
    externalTrafficPolicy: "Cluster"
    headless: false
    objectMetaOverrides:
      labels:
        custom: label
      annotations:
        custom: annotations

  aggregatorSpec:
    count: 2
    height: 0.5
    storageGB: 150
    storageClass: ocs-storagecluster-ceph-rbd

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label
    globalVariables:
        http_api: "ON"
        http_proxy_port: "8081"

  leafSpec:
    count: 2
    height: 0.5
    storageGB: 150
    storageClass: ocs-storagecluster-ceph-rbd

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label

    globalVariables:
      http_api: "ON"
      http_proxy_port: "8081"
