apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: memsql-ui
  name: sqlmem-ui
  namespace: singlestore
spec:
  host: sqlmem-ui.vnpt.vn
  port:
    targetPort: 8080
  tls:
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    certificate: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: None
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: memsql-ui
    weight: 100
  wildcardPolicy: None
